### ISSUE TITLE
Request for adding the German anime Site "Aniworld"

### ISSUE THREAD

**Issue by JoeneckSpoeneck** [kodjodevf/mangayomi-extensions#10]
### Source name

Aniworld

### Source link

https://aniworld.to/

### Source language

Deutsch (German)

### Other details

If I remember correctly, you have to register on the website to be able to watch videos in an app. (The extension already exists in the Aniyomi app, that's how I know (but I use Linux and Aniyomi doesn't run on Linux)) In any case, I would be very happy if this site could be implemented, because it is the best manga/anime app on Linux and would make the app even better for me =)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/kodjodevf/mangayomi-extensions/) and verified it does not appear in the code base.

**Comment by kodjodevf** [comment]
Added!
