### ISSUE TITLE
Request for adding the German anime site "Aniflix"

### ISSUE THREAD

**Issue by JoeneckSpoeneck** [kodjodevf/mangayomi-extensions#11]
### Source name

Aniflix

### Source link

https://aniflix.cc/

### Source language

Deutsch (German)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/kodjodevf/mangayomi-extensions/) and verified it does not appear in the code base.

**Comment by JoeneckSpoeneck** [comment]
Hey, thank you very much first of all! But there is one thing that is a bit problematic: On the Aniflix site, if you want to see more episodes, you have to click on "load more" (see screenshot 1). Only the first 24 episodes are shown. That is also the case in the Mangayomi app but in the app, I can't load more Episodes (see screenshot 2). Is it possible for you to fix this? That Problem doesn't exist in the Aniyomi app on Android (see screenshot 3), so I think there must be a way to fix this. I hope this doesn't annoy you or anything, but could you please take a look at this issue?
![Screenshot_20240103_193148-1](https://github.com/kodjodevf/mangayomi-extensions/assets/139454563/de62ba9e-57a0-49cd-818e-4dd655a21e6b)
![Screenshot_20240103_193037](https://github.com/kodjodevf/mangayomi-extensions/assets/139454563/17be10c1-c917-4a46-8e2c-a7f3d4c4915c)
![Screenshot_20240103_194849_Aniyomi](https://github.com/kodjodevf/mangayomi-extensions/assets/139454563/a01e8cc7-f736-468e-9174-2e11c3f842a6)

**Comment by kodjodevf** [comment]
Fixed!

**Comment by JoeneckSpoeneck** [comment]
Thank you!!
