### ISSUE TITLE
All manga from bato.to extension don’t open and get runtime error

### ISSUE THREAD

**Issue by bolabola6789** [kodjodevf/mangayomi-extensions#15]
### Source information

Bato.to. 0.0.55

### Source language

English

### Steps to reproduce

Try to read any manga from this source

### Expected behavior

The manga (images) load normally

### Actual behavior

![IMG_0493](https://github.com/kodjodevf/mangayomi-extensions/assets/105188534/c31e4054-22b3-43d7-b720-3d1479cae50a)

### Mangayomi version

0.1.61

### Device

iPad Mini 6, iPadOS 17.0

### Other details

App installed via TrollStore

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/kodjodevf/mangayomi/issues/new/choose).

**Comment by kodjodevf** [comment]
Fixed!
