### ISSUE TITLE
Chapters not loading

### ISSUE THREAD

**Issue by Smiley1830** [kodjodevf/mangayomi-extensions#25]
### Source information

Mangakakalot 0.0.2

### Source language

English

### Steps to reproduce

![image](https://github.com/kodjodevf/mangayomi/assets/95736297/84ac3abb-da08-4e99-a1cb-ef6cf014c461)
The manga I selected have no chapters loaded in
Using webview works but it's really inconvenient 
Migration isn't an option so it's difficult to find the same manga on different extension

### Expected behavior

The manga should have loaded in all chapters that are available.

### Actual behavior

Half of the manga I selected have no chapters even though they are in the same extension as the others and have been ongoing for some time.
![image](https://github.com/kodjodevf/mangayomi/assets/95736297/bc4205c3-df17-481e-9c4e-fc871e18dd9f)

### Mangayomi version

0.1.61

### Device

Windows 11/Samsung S23+ (Android 14)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/kodjodevf/mangayomi/issues/new/choose).

**Comment by kodjodevf** [comment]
Fixed!!
