### ISSUE TITLE
Can't search in Yomiroll

### ISSUE THREAD

**Issue by JoeneckSpoeneck** [kodjodevf/mangayomi-extensions#30]
### Source information

Yomiroll 0.0.1 (All)

### Source language

All

### Steps to reproduce

1. Under "Browse", click on the "Anime Sources" Tab, than click on "Yomiroll" 2. Type somthing in the searchbar.

### Expected behavior

Displays the Anime you've searched for.

### Actual behavior

Getting an error message as shown in the screenshot:

![Screenshot from 2024-02-12 00-25-09](https://github.com/kodjodevf/mangayomi-extensions/assets/139454563/9fef0874-9483-402e-ac70-df242c451bc1)

### Mangayomi version

0.1.75

### Device

HP Laptop, Linux

### Other details

My Linux is Opensuse Tumbleweed and I installed Mangayomi with the Appimage

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/kodjodevf/mangayomi/issues/new/choose).

**Comment by kodjodevf** [comment]
Fixed!!
