### ISSUE TITLE
Anime Extension not working properly

### ISSUE THREAD

**Issue by Ivela183** [kodjodevf/mangayomi-extensions#39]
### Source information

Yomiroll 0.0.2

### Source language

All

### Steps to reproduce

1.Load any anime from the Yomiroll extension.

### Expected behavior

It should start playing the video once an episode is selected.

### Actual behavior

An "Error" text appears in the middle.
![image](https://github.com/kodjodevf/mangayomi-extensions/assets/128411935/4c30682f-b6b8-478d-91d2-48c7a1355f57)

### Mangayomi version

0.1.85

### Device

Windows 11, Samsung S23+ Android 14

### Other details

Other extension was not working properly before, like 9AnimeTv, but most extension are working now except Yomiroll.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/kodjodevf/mangayomi/issues/new/choose).

**Comment by kodjodevf** [comment]
Extension Removed!
