### ISSUE TITLE
Aniwave extension not working properly

### ISSUE THREAD

**Issue by KellZek** [kodjodevf/mangayomi-extensions#40]
### Source information

Aniwave 0.0.65

### Source language

Englisn

### Steps to reproduce

1. Go on the extension page (Browse > Aniwave)
2. Open any anime page

### Expected behavior

It should load all available episodes and list them

### Actual behavior

The following error gets returned

![Screenshot_2024-04-03-20-10-29-150_com kodjodevf mangayomi](https://github.com/kodjodevf/mangayomi-extensions/assets/158817576/87acad79-0b23-4f7b-bae5-9fc0eea779b4)

### Mangayomi version

Beta (0.2.0)

### Device

Xiaomi Redmi Note 11 Pro

### Other details

The problem also includes the animes saved in the library. The webview and the main pages work fine, but opening any anime page sometimes makes the main page not load at all

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/kodjodevf/mangayomi/issues/new/choose).

**Comment by kodematthieu** [comment]
Found the issue, it's at [#L180](https://github.com/kodjodevf/mangayomi-extensions/blob/main/dart/anime/src/en/aniwave/aniwave.dart#L180). It tries to parse HTML response as JSON and throws syntax error as a result

**Comment by kodjodevf** [comment]
Fixed!
