### ISSUE TITLE
Adding English nsfw source: hanime tv

### ISSUE THREAD

**Issue by maddovr** [kodjodevf/mangayomi-extensions#82]
### Source name

Hanime

### Source link

https://hanime.tv

### Source language

English

### Other details

+18/NSFW = yes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/kodjodevf/mangayomi-extensions/) and verified it does not appear in the code base.

**Comment by O-Codex** [comment]
He is a **Muslim**, how can you ask him to add forbidden materials to his application? _We do not want him to add them._
